name: soap_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  json_annotation: ^4.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons: 0.13.1
  mime_type: ^1.0.0
  path_provider: ^2.1.2
  flutter_conditional_rendering: ^2.0.0
  flutter_i18n: ^0.35.0
  image_gallery_saver: 2.0.3
  get: ^4.6.6
  permission_handler: ^11.2.0
  jpush_flutter: ^2.5.0
  lottie: ^3.0.0
  flutter_cupertino_datetime_picker: ^3.0.0
  sentry_flutter: ^7.14.0
  throttling: ^2.0.1
  styled_text: ^8.1.0
  auto_animated: ^3.2.0
  flutter_displaymode: ^0.6.0
  share: ^2.0.4
  flutter_advanced_switch: ^3.0.1
  extended_text: ^12.0.1
  material_tag_editor: ^0.1.2
  blurhash: ^1.1.1
  http_parser: ^4.0.2
  uuid: ^4.3.3
  crypto: ^3.0.3
  palette_generator: ^0.3.2
  decimal: ^2.3.3
  wechat_assets_picker: ^9.0.0-dev.2
  exif: ^3.3.0
  url_launcher: ^6.2.3
  enum_to_string: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.0.0-beta.22
  bot_toast: ^4.1.3
  waterfall_flow: ^3.0.3
  extended_list: ^3.0.1
  extended_image: ^8.2.0
  extended_nested_scroll_view: ^6.2.1
  tab_indicator_styler: ^2.0.0-null-safety
  modal_bottom_sheet: ^3.0.0-pre

  shared_preferences: ^2.2.2
  validators: ^3.0.0
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.9
  graphql_flutter: 5.2.0-beta.6
  gql: 1.0.1-alpha+1705114622973
  flutter_feather_icons: 2.0.0+1
  cupertino_icons: ^1.0.6
  touchable_opacity: ^1.2.0
  jiffy: ^6.2.1
  octo_image: ^2.0.0
  flutter_mobx: ^2.2.0+2
  mobx: ^2.3.0+1
  shelf_proxy: ^1.0.4
  like_button: ^2.0.4
  pull_to_refresh: ^2.0.0
  line_icons: ^2.0.3
  flutter_staggered_animations: ^1.1.1
  keframe: 3.0.0
  fps_monitor: ^2.0.0
  flutter_blurhash: ^0.8.2
  searchfield: ^0.9.0
  decorated_icon: ^1.2.1
  ionicons: ^0.2.2
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0
  flutter_bounce: ^1.1.0
  flutter_bounceable: ^1.0.2
  photo_view: 0.14.0
dependency_overrides:
  photo_manager: ^3.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mobx_codegen: ^2.6.0+1
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - .env
    - assets/images/empty.png
    - assets/images/vip.png

    - assets/feather/thumbs-up.svg
    - assets/feather/chevron-left.svg
    - assets/feather/plus.svg
    - assets/feather/settings.svg
    - assets/feather/chevron-right.svg
    - assets/feather/camera.svg
    - assets/feather/star.svg
    - assets/feather/star-fill.svg

    - assets/remix/home-2.svg
    - assets/remix/add-circle.svg
    - assets/remix/user.svg
    - assets/remix/camera-3-line.svg
    - assets/remix/camera-lens-line.svg
    - assets/remix/heart-3-line.svg
    - assets/remix/heart-3-fill.svg
    - assets/remix/tag.svg
    - assets/remix/weibo-line.svg
    - assets/remix/github-line.svg
    - assets/remix/image-edit-line.svg
    - assets/remix/delete-bin-5-line.svg
    - assets/remix/lock-fill.svg
    - assets/remix/share-line.svg
    - assets/remix/star-line.svg
    - assets/remix/star-fill.svg
    - assets/remix/checkbox-circle-fill.svg

    - assets/svg/weibo.svg
    - assets/svg/github.svg
    - assets/svg/null.svg
    - assets/svg/plus.svg
    - assets/svg/home.svg
    - assets/svg/vip.svg
    - assets/svg/hzfe.svg
    - assets/svg/like.svg
    - assets/svg/view.svg
    - assets/svg/planet.svg
    - assets/svg/hexagon.svg
    - assets/svg/female.svg
    - assets/svg/male.svg

    - assets/svg/constellation/capricorn.svg
    - assets/svg/constellation/aquarius.svg
    - assets/svg/constellation/pisces.svg
    - assets/svg/constellation/aries.svg
    - assets/svg/constellation/taurus.svg
    - assets/svg/constellation/gemini.svg
    - assets/svg/constellation/cancer.svg
    - assets/svg/constellation/leo.svg
    - assets/svg/constellation/virgo.svg
    - assets/svg/constellation/libra.svg
    - assets/svg/constellation/scorpio.svg
    - assets/svg/constellation/sagittarius.svg

    - assets/svg/emoji/garden.svg

    - assets/svg/ordinary.svg

    - assets/lottie/cat.json
    - assets/lottie/mail-send.json
    - assets/lottie/coffee-time.json

    - assets/svg/home-ternav.svg
    - assets/svg/user-ternav.svg
    - assets/svg/add-ternav.svg
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/400W.ttf
        - asset: assets/fonts/Rubik/300W.ttf
          weight: 300
        - asset: assets/fonts/Rubik/500W.ttf
          weight: 500
        - asset: assets/fonts/Rubik/600W.ttf
          weight: 600
        - asset: assets/fonts/Rubik/700W.ttf
          weight: 700
    # - family: 江城圆体
    #   fonts:
    #     - asset: assets/fonts/江城圆体/400W.ttf
    #     - asset: assets/fonts/江城圆体/300W.ttf
    #       weight: 300
    #     - asset: assets/fonts/江城圆体/500W.ttf
    #       weight: 500
    #     - asset: assets/fonts/江城圆体/600W.ttf
    #       weight: 600
    # - family: 思源宋体
    #   fonts:
    #     - asset: assets/fonts/思源宋体/400W.otf
    #     - asset: assets/fonts/思源宋体/300W.otf
    #       weight: 300
    #     - asset: assets/fonts/思源宋体/500W.otf
    #       weight: 500
    #     - asset: assets/fonts/思源宋体/600W.otf
    #       weight: 600
flutter_native_splash:
  image: assets/images/splash.gif
  color: "ffffff"
  color_dark: "2e186a"
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
