name: soap_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 < 3.0.0"

dependencies:
  json_annotation: ^4.0.0
  flutter:
    sdk: flutter

  sentry_flutter: ^5.1.0-beta.1
  throttling: ^1.0.0
  styled_text: ^3.0.0
  auto_animated: ^3.0.0
  flutter_displaymode: ^0.3.1-nullsafety.0
  share: ^2.0.1
  flutter_advanced_switch: ^2.0.2+2
  extended_text: ^6.0.6
  material_tag_editor: ^0.1.1
  blurhash: ^0.3.0-nullsafety.0
  http_parser: ^4.0.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  intl: ^0.17.0
  palette_generator: ^0.3.0
  decimal: ^1.1.0
  wechat_assets_picker: ^5.5.2
  exif: ^2.1.0
  url_launcher: ^6.0.3
  enum_to_string: ^2.0.1
  flutter_dotenv: ^4.0.0-nullsafety.1
  flutter_inappwebview: ^5.3.2
  bot_toast: ^4.0.1
  waterfall_flow: ^3.0.1
  extended_list: ^3.0.0
  extended_image: ^4.1.0
  extended_nested_scroll_view: ^3.0.0
  tab_indicator_styler: ^2.0.0-null-safety
  modal_bottom_sheet: ^2.0.0

  shared_preferences: ^2.0.5
  validators: ^3.0.0
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  flutter_native_splash: 1.1.8+4
  graphql_flutter: 5.0.0-nullsafety.2
  gql: 0.13.0-nullsafety.2
  flutter_feather_icons: 2.0.0+1
  cupertino_icons: ^1.0.3
  touchable_opacity: ^1.2.0
  flutter_easyrefresh: ^2.2.1
  jiffy: ^4.1.0
  octo_image: ^1.0.0+1
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  shelf_proxy: ^1.0.0
  like_button: ^2.0.2
  pull_to_refresh:
    git:
      url: https://github.com/peng8350/flutter_pulltorefresh
      path: .
      ref: nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.0
  mobx_codegen: ^2.0.1+3
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/empty.png
    - assets/images/vip.png

    - assets/feather/thumbs-up.svg
    - assets/feather/chevron-left.svg
    - assets/feather/plus.svg
    - assets/feather/settings.svg
    - assets/feather/chevron-right.svg
    - assets/feather/camera.svg
    - assets/feather/star.svg
    - assets/feather/star-fill.svg

    - assets/remix/home-2.svg
    - assets/remix/add-circle.svg
    - assets/remix/user.svg
    - assets/remix/camera-3-line.svg
    - assets/remix/camera-lens-line.svg
    - assets/remix/heart-3-line.svg
    - assets/remix/heart-3-fill.svg
    - assets/remix/tag.svg
    - assets/remix/weibo-line.svg
    - assets/remix/github-line.svg
    - assets/remix/image-edit-line.svg
    - assets/remix/delete-bin-5-line.svg
    - assets/remix/lock-fill.svg
    - assets/remix/share-line.svg
    - assets/remix/star-line.svg
    - assets/remix/star-fill.svg
    - assets/remix/checkbox-circle-fill.svg

    - assets/svg/weibo.svg
    - assets/svg/github.svg
    - assets/svg/null.svg
    - assets/svg/plus.svg
    - assets/svg/home.svg
    - assets/svg/vip.svg
    - assets/svg/hzfe.svg
    - assets/svg/like.svg
    - assets/svg/view.svg
    - assets/svg/planet.svg
    - assets/svg/hexagon.svg
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/400W.ttf
        - asset: assets/fonts/Rubik/300W.ttf
          weight: 300
        - asset: assets/fonts/Rubik/500W.ttf
          weight: 500
        - asset: assets/fonts/Rubik/600W.ttf
          weight: 600
        - asset: assets/fonts/Rubik/700W.ttf
          weight: 700
    - family: 江城圆体
      fonts:
        - asset: assets/fonts/江城圆体/400W.ttf
        - asset: assets/fonts/江城圆体/300W.ttf
          weight: 300
        - asset: assets/fonts/江城圆体/500W.ttf
          weight: 500
        - asset: assets/fonts/江城圆体/600W.ttf
          weight: 600
    # - family: 思源宋体
    #   fonts:
    #     - asset: assets/fonts/思源宋体/400W.otf
    #     - asset: assets/fonts/思源宋体/300W.otf
    #       weight: 300
    #     - asset: assets/fonts/思源宋体/500W.otf
    #       weight: 500
    #     - asset: assets/fonts/思源宋体/600W.otf
    #       weight: 600

flutter_native_splash:
  image: assets/images/splash.gif
  color: "ffffff"
  color_dark: "2e186a"
