name: soap_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 < 3.0.0"

dependencies:
  json_annotation: ^4.0.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.3.1-nullsafety.0
  share: ^2.0.1
  flutter_advanced_switch: ^2.0.2+2
  extended_text: ^6.0.6
  material_tag_editor: ^0.1.1
  blurhash: ^0.3.0-nullsafety.0
  http_parser: ^4.0.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  intl: ^0.17.0
  palette_generator: ^0.3.0
  decimal: ^1.1.0
  wechat_assets_picker: ^5.5.1
  exif: ^2.1.0
  url_launcher: ^6.0.3
  enum_to_string: ^2.0.1
  flutter_dotenv: ^4.0.0-nullsafety.1
  flutter_inappwebview: ^5.3.2
  bot_toast: ^4.0.1
  waterfall_flow: ^3.0.1
  extended_list: ^3.0.0
  extended_image: ^4.0.1
  extended_nested_scroll_view: ^3.0.0
  tab_indicator_styler: ^2.0.0-null-safety
  modal_bottom_sheet: ^2.0.0

  shared_preferences: ^2.0.5
  validators: ^3.0.0
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  flutter_native_splash: 1.1.8+4
  graphql_flutter: 5.0.0-nullsafety.2
  gql: 0.13.0-nullsafety.2
  flutter_feather_icons: 2.0.0+1
  cupertino_icons: ^1.0.2
  touchable_opacity: ^1.2.0
  flutter_easyrefresh: ^2.2.1
  jiffy: ^4.1.0
  flutter_keyboard_visibility: ^5.0.1
  octo_image: ^1.0.0+1
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  shelf_proxy: ^1.0.0
  like_button: ^2.0.2
  pull_to_refresh:
    git:
      url: https://github.com/peng8350/flutter_pulltorefresh
      path: .
      ref: nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.0
  mobx_codegen: ^2.0.1+3
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/empty.png
    - assets/feather/thumbs-up.svg
    - assets/feather/chevron-left.svg
    - assets/feather/plus.svg
    - assets/feather/settings.svg
    - assets/feather/chevron-right.svg
    - assets/feather/camera.svg
    - assets/remix/home-2.svg
    - assets/remix/add-circle.svg
    - assets/remix/user.svg
    - assets/remix/camera-3-line.svg
    - assets/remix/camera-lens-line.svg
    - assets/remix/heart-3-line.svg
    - assets/remix/heart-3-fill.svg
    - assets/remix/tag.svg
    - assets/remix/weibo-line.svg
    - assets/remix/github-line.svg
    - assets/remix/image-edit-line.svg
    - assets/remix/delete-bin-5-line.svg
    - assets/remix/lock-fill.svg
    - assets/remix/share-line.svg
    - assets/weibo.svg
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

flutter_native_splash:
  image: assets/images/splash.gif
  color: "ffffff"
  android_disable_fullscreen: true
